# -*- coding: utf-8 -*-
"""自殺偵測.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZE0tOrVR9dWD7mgRv2kjtXpCtldxzSp2
"""

# -*- coding: utf-8 -*-
"""
自殺防治語料 - 辭典繁簡轉換與 CKIP 斷詞、詞性標註流程
"""

!pip install opencc-python-reimplemented
!pip install ckip-transformers
!pip install xlsxwriter

from google.colab import drive
drive.mount('/content/drive')
import os
import re
import pandas as pd
import torch
from opencc import OpenCC
from ckip_transformers.nlp import CkipWordSegmenter, CkipPosTagger
from tqdm import tqdm

# ==========================================
# 1. 檔案路徑設定
# ==========================================
INPUT_FILE = '/content/drive/MyDrive/語料期末/step1_cleaned_data.xlsx'

# 外部辭典路徑
DICT_RAW_FILE = '/content/drive/MyDrive/Chinese suicide dictionary.xlsx'
DICT_TC_FILE = '/content/drive/MyDrive/Chinese suicide dictionary_TC_v2.xlsx'

# 輸出路徑
OUTPUT_FILE = '/content/drive/MyDrive/語料期末/step2_segmented_data_FIXED_v2.xlsx'

# ==========================================
# 2. 輔助函式定義
# ==========================================
def fix_broken_tokens(token_str, protect_list):
    """
    關鍵字修復函式：將被 CKIP 錯誤切分的領域關鍵字重新黏合。
    """
    fixed_str = token_str
    for word in protect_list:
        if len(word) < 2:
            continue

        # 效能優化：先確認字串首字是否存在，再執行正規表達式替換
        if word[0] in fixed_str:
            pattern = r"\s*".join([re.escape(char) for char in word])
            fixed_str = re.sub(pattern, word, fixed_str, flags=re.IGNORECASE)

    return fixed_str

# ==========================================
# 3. 主程式執行邏輯
# ==========================================
def main():
    # --- A. 外部辭典處理 (簡體轉繁體) ---
    if not os.path.exists(DICT_TC_FILE) and os.path.exists(DICT_RAW_FILE):
        print("[系統提示] 尚未建立繁體辭典，正在執行簡體至繁體轉換程序...")
        converter = OpenCC('s2t')
        xls = pd.ExcelFile(DICT_RAW_FILE)

        with pd.ExcelWriter(DICT_TC_FILE, engine='xlsxwriter') as writer:
            for sheet_name in xls.sheet_names:
                df_sheet = pd.read_excel(xls, sheet_name=sheet_name, header=None)
                words_sc = df_sheet.iloc[:, 0].astype(str).tolist()
                words_tc = [converter.convert(word) for word in words_sc]
                pd.DataFrame({0: words_tc}).to_excel(writer, sheet_name=sheet_name, header=False, index=False)
        print(f"[執行成功] 繁體辭典已生成並儲存至: {DICT_TC_FILE}")

    # --- B. 建構領域關鍵字保護清單 ---
    print("[系統提示] 正在載入關鍵字保護清單...")
    words_to_protect = set()

    # 載入外部繁體辭典
    if os.path.exists(DICT_TC_FILE):
        xls = pd.ExcelFile(DICT_TC_FILE)
        for sheet_name in xls.sheet_names:
            df_sheet = pd.read_excel(xls, sheet_name=sheet_name, header=None)
            words = df_sheet.iloc[:, 0].dropna().astype(str).tolist()
            words_to_protect.update(words)
    else:
        print(f"[警告] 找不到外部辭典檔案: {DICT_TC_FILE}，將僅使用內部在地化清單。")

    # 載入在地化社群用語 (PTT Slang)
    PTT_SLANG = [
        '登出', '登出人生', '強制登出', '重刷', '重刷首抽', '首抽',
        '刪號', '刪帳號', '畢業', '提早畢業', '去世界盡頭', '睡著', '長眠',
        '不痛了', '無痛登出', '去當天使', 'OD', 'od', 'Overdose', 'overdose',
        '史蒂諾斯', '小史', 'FM2', 'Fm2', 'fm2', 'Xanax', 'xanax',
        '贊安諾', '小橘', '百憂解', '利他能', '吞藥', '藥罐子', '斷藥',
        '燒炭', '炭盆', '火盆', '烤肉', '氦氣', '氮氣',
        '繩子', '上吊', '童軍繩', '跳樓', '頂樓', '天台', '小飛俠',
        '割腕', '割手', '劃手', '自S', '自s', 'ZS', 'zs',
        '廢物', '垃圾', '沒用', '累贅', '行屍走肉', '空殼', '黑洞',
        '深淵', '絕望', '好累', '撐不住', '崩潰', '交代後事', '遺書'
    ]
    words_to_protect.update(PTT_SLANG)

    # 依據字串長度進行降冪排序，確保長詞優先匹配
    sorted_protect_list = sorted(list(words_to_protect), key=len, reverse=True)
    print(f"[系統提示] 關鍵字保護清單建構完成，共計 {len(sorted_protect_list)} 個詞彙。")

    # --- C. CKIP 模型初始化 ---
    use_cuda = torch.cuda.is_available()
    device = 0 if use_cuda else -1
    batch_size = 256 if use_cuda else 32

    print(f"[系統提示] 正在初始化 CKIP 模型。硬體加速 (GPU): {use_cuda}，批次大小: {batch_size}")
    ws_driver = CkipWordSegmenter(model="bert-base", device=device)
    pos_driver = CkipPosTagger(model="bert-base", device=device)

    # --- D. 執行斷詞與詞性標註 ---
    if not os.path.exists(INPUT_FILE):
        print(f"[錯誤] 找不到輸入檔案: {INPUT_FILE}")
        return

    df = pd.read_excel(INPUT_FILE)
    texts = df['cleaned_content'].astype(str).tolist()

    print("[階段 2-A] 執行初步斷詞 (Word Segmentation)...")
    ws_results = ws_driver(texts, batch_size=batch_size, use_delim=False)

    print("[階段 2-B] 執行領域關鍵字修復與空值清理...")
    clean_ws_tokens_list = []
    for tokens in tqdm(ws_results, desc="修復與清理進度"):
        raw_str = " ".join(tokens)
        fixed_str = fix_broken_tokens(raw_str, sorted_protect_list)
        fixed_tokens = fixed_str.split(" ")

        # 剔除純空白 Token，確保後續 POS 標記能精準對齊
        sanitized_tokens = [t for t in fixed_tokens if t.strip() != ""]
        clean_ws_tokens_list.append(sanitized_tokens)

    print("[階段 2-C] 執行詞性標註 (Part-of-Speech Tagging)...")
    pos_results = pos_driver(clean_ws_tokens_list, batch_size=batch_size, use_delim=False)

    # --- E. 匯出結果與驗收檢查 ---
    df['ckip_tokens'] = [" ".join(ws) for ws in clean_ws_tokens_list]
    df['pos_tags'] = [" ".join(pos) for pos in pos_results]

    cols_to_save = ['final_label', 'cleaned_content', 'ckip_tokens', 'pos_tags']
    df[cols_to_save].to_excel(OUTPUT_FILE, index=False)

    print(f"[執行成功] Step 2 處理完畢，斷詞資料已安全儲存至: {OUTPUT_FILE}")

    # 執行最終抽樣驗收
    print("\n[系統檢查] 抽樣檢查特定關鍵字之詞性標註結果:")
    check_list = ['OD', 'FM2', '自殺', '痛苦', '絕望']
    found_count = 0

    for idx, row in df.head(100).iterrows():
        ts = str(row['ckip_tokens']).split()
        ps = str(row['pos_tags']).split()

        for w in check_list:
            if w in ts:
                i = ts.index(w)
                if i < len(ps):
                    print(f"  - 尋獲關鍵字 [{w}]，對應詞性為: {ps[i]}")
                    found_count += 1
        if found_count >= 5:
            break

if __name__ == '__main__':
    main()

# -*- coding: utf-8 -*-
"""
語言學特徵工程與統計顯著性檢定
(Linguistic Feature Engineering and Statistical Analysis)
"""

import os
import numpy as np
import pandas as pd
from scipy import stats
from collections import defaultdict, Counter
from tqdm import tqdm
from opencc import OpenCC

# ==========================================
# 1. 檔案路徑設定 (加入 _github_v2 後綴以保護原始資料)
# ==========================================
INPUT_FILE = '/content/drive/MyDrive/語料期末/step2_segmented_data_FIXED.xlsx'
DICT_FILE = '/content/drive/MyDrive/Chinese suicide dictionary.xlsx'

OUTPUT_DATA = '/content/drive/MyDrive/語料期末/final_dataset_for_ML_github_v2.xlsx'
OUTPUT_STATS = '/content/drive/MyDrive/語料期末/academic_stats_report_FULL_github_v2.xlsx'

# ==========================================
# 2. 語言學特徵詞庫定義 (Linguistic Lexicons)
# ==========================================
ABSOLUTE_WORDS = set([
    '絕對', '絕對地', '所有', '全部', '都', '總是', '一直', '永遠', '完全', '完整',
    '徹底', '持續', '不斷', '肯定', '一定', '整個', '曾經', '每個', '每個人', '所有人',
    '大家', '一切', '什麼都', '滿', '必須', '必定', '從不', '絕不', '沒什麼', '一無所有',
    '統統', '百分之百', '毫無'
])

NEGATION_WORDS = set([
    '不', '沒', '無', '非', '別', '未', '莫', '勿', '否', '不再', '沒有', '無法',
    '不行', '不是', '不用', '不要', '休想', '沒了'
])

FIRST_PERSON = set([
    '我', '我的', '俺', '本人', '本', '我自己', '自己', '老子', '本魯', '小弟',
    '小妹', '敝人', '在下'
])


FUTURE_WORDS = {'明天', '未來', '以後', '將來', '下週', '明年', '之後', '後天', '下個月'}

# ==========================================
# 3. 統計輔助函式 (Effect Size Calculations)
# ==========================================
def get_cohens_d(group1, group2):
    """計算 Cohen's d (參數型效果量)"""
    n1, n2 = len(group1), len(group2)
    v1, v2 = np.var(group1, ddof=1), np.var(group2, ddof=1)
    pooled_sd = np.sqrt(((n1 - 1) * v1 + (n2 - 1) * v2) / (n1 + n2 - 2))
    if pooled_sd == 0:
        return 0
    return (np.mean(group1) - np.mean(group2)) / pooled_sd

def get_cliffs_delta(group1, group2):
    """計算 Cliff's delta (非參數型效果量)"""
    n1, n2 = len(group1), len(group2)
    g1, g2 = np.array(group1), np.array(group2)
    diff = np.expand_dims(g1, axis=1) - np.expand_dims(g2, axis=0)
    delta = (np.sum(diff > 0) - np.sum(diff < 0)) / (n1 * n2)
    return delta

def interpret_delta(delta):
    """解讀 Cliff's delta 效果等級"""
    delta = abs(delta)
    if delta < 0.147: return "Negligible"
    if delta < 0.33: return "Small"
    if delta < 0.474: return "Medium"
    return "Large"

# ==========================================
# 4. 主程式執行邏輯
# ==========================================
def main():
    cc = OpenCC('s2t')

    if not (os.path.exists(INPUT_FILE) and os.path.exists(DICT_FILE)):
        print(f"[錯誤] 找不到輸入語料或辭典檔案，請確認掛載路徑。")
        return

    print(f"[系統資訊] 載入語料檔案: {INPUT_FILE}")
    df = pd.read_excel(INPUT_FILE)
    df['ckip_tokens'] = df['ckip_tokens'].fillna("").astype(str)
    df['pos_tags'] = df['pos_tags'].fillna("").astype(str)

    # --- [階段 1] 學術詞性檢查 ---
    print("\n[階段 1] 檢核 CKIP 詞性標記完整性")
    all_tags_counter = Counter()
    for tags_str in df['pos_tags']:
        all_tags_counter.update(tags_str.split())

    target_tags = {
        'Nh': 'Self/Social (代名詞)',
        'VE': 'Cognition (認知動詞)',
        'Cbb': 'Causation (因果連詞)',
        'VH': 'Emotion/State (狀態)',
        'Nd': 'Time (時間)',
        'Nb': 'Social (人名)'
    }
    for t, desc in target_tags.items():
        status = "存在" if all_tags_counter[t] > 0 else "缺失"
        print(f"    - {t:<3} [{desc}]: {status}")

    # --- [階段 2] 載入辭典  ---
    print("\n[階段 2] 載入自殺防治辭典 (執行清洗與合併邏輯)...")
    suicide_dict = defaultdict(set)
    xls = pd.ExcelFile(DICT_FILE)

    BLACKLIST_CATS = {'CATEGORY', 'category', 'WORD', 'word', 'Sheet1'}

    if len(xls.sheet_names) > 1:
        print(f"    - 偵測為多分頁結構 (共 {len(xls.sheet_names)} 類)")
        for sheet in xls.sheet_names:
            clean_cat = sheet.strip().upper()
            if clean_cat in BLACKLIST_CATS:
                continue
            try:
                d_df = pd.read_excel(xls, sheet_name=sheet, header=None)
                words_sc = d_df.iloc[:, 0].dropna().astype(str).tolist()
                suicide_dict[clean_cat].update([cc.convert(w) for w in words_sc])
            except Exception:
                continue
    else:
        print("    - 偵測為單分頁結構")
        try:
            d_df = pd.read_excel(xls, sheet_name=0, header=None)
            if d_df.shape[1] >= 2:
                for idx, row in d_df.iterrows():
                    word_sc = str(row[0]).strip()
                    raw_cat = str(row[1]).strip()
                    clean_cat = raw_cat.upper()

                    if clean_cat in BLACKLIST_CATS or clean_cat == 'NAN' or word_sc.lower() == 'nan':
                        continue
                    suicide_dict[clean_cat].add(cc.convert(word_sc))
            else:
                print("    - 警告：偵測為單欄模式，特徵將歸類為 GENERAL")
                words_sc = d_df.iloc[:, 0].dropna().astype(str).tolist()
                suicide_dict['GENERAL'] = set([cc.convert(w) for w in words_sc])
        except Exception as e:
            print(f"    - 辭典讀取發生錯誤: {e}")

    dict_cats = sorted(suicide_dict.keys())
    print(f"    - 辭典清洗合併完成，最終有效類別數 ({len(dict_cats)} 類): {dict_cats}")

    # --- [階段 3] 計算特徵密度  ---
    print("\n[階段 3] 執行語言學與領域特徵萃取 (Feature Density)...")
    feature_rows = []

    for idx, row in tqdm(df.iterrows(), total=len(df), desc="特徵運算進度"):
        tokens = row['ckip_tokens'].split()
        tags = row['pos_tags'].split()
        doc_len = len(tokens) if len(tokens) > 0 else 1

        abs_count = sum(1 for t in tokens if t in ABSOLUTE_WORDS)
        neg_count = sum(1 for t in tokens if t in NEGATION_WORDS)

        pos_counts = defaultdict(int)
        future_count = 0


        for t, tag in zip(tokens, tags):
            if tag == 'Nh' and t in FIRST_PERSON:
                pos_counts['Self_Focus'] += 1
            elif (tag == 'Nh' and t not in FIRST_PERSON) or tag == 'Nb':
                pos_counts['Social_Ref'] += 1

            if tag == 'VE' or tag == 'Cbb':
                pos_counts['Cognition'] += 1

            if tag.startswith('V'):
                pos_counts['Verb_Total'] += 1

            if tag.startswith('VH'):
                pos_counts['Adj_State'] += 1

            if tag == 'Nd':
                pos_counts['Time_Noun'] += 1
                if t in FUTURE_WORDS:
                    future_count += 1

            if tag == 'I':
                pos_counts['Interjection'] += 1

        features = {
            'Len': doc_len,
            'Ling_Absolutist': (abs_count / doc_len) * 100,
            'Ling_Negation': (neg_count / doc_len) * 100,
            'Ling_Future': (future_count / doc_len) * 100,
            'POS_Self_Focus': (pos_counts['Self_Focus'] / doc_len) * 100,
            'POS_Social_Ref': (pos_counts['Social_Ref'] / doc_len) * 100,
            'POS_Cognition': (pos_counts['Cognition'] / doc_len) * 100,
            'POS_Verb_Total': (pos_counts['Verb_Total'] / doc_len) * 100,
            'POS_Adj_State': (pos_counts['Adj_State'] / doc_len) * 100,
            'POS_Time_Noun': (pos_counts['Time_Noun'] / doc_len) * 100,
            'POS_Interjection': (pos_counts['Interjection'] / doc_len) * 100,
        }


        total_dict = 0
        for cat in dict_cats:
            c = sum(1 for t in tokens if t in suicide_dict[cat])
            features[f'Dict_{cat}'] = (c / doc_len) * 100
            total_dict += c

        features['Dict_Total_Density'] = (total_dict / doc_len) * 100
        feature_rows.append(features)

    df_features = pd.DataFrame(feature_rows)
    df_final = pd.concat([df, df_features], axis=1)
    df_final.to_excel(OUTPUT_DATA, index=False)
    print(f"\n[執行成功] 特徵資料集已匯出至: {OUTPUT_DATA}")

    # --- [階段 4] 統計檢定與效果量分析 ---
    print("\n[階段 4] 執行統計顯著性檢定 (Mann-Whitney U, Cohen's d, Cliff's delta)...")

    stats_data = []
    feature_cols = list(df_features.columns)
    if 'Len' in feature_cols:
        feature_cols.remove('Len')

    group_s = df_final[df_final['final_label'] == 1]
    group_c = df_final[df_final['final_label'] == 0]

    for col in feature_cols:
        val_s = group_s[col].values
        val_c = group_c[col].values

        try:
            _, p = stats.mannwhitneyu(val_s, val_c, alternative='two-sided')
        except Exception:
            p = 1.0

        d_val = get_cohens_d(val_s, val_c)
        delta_val = get_cliffs_delta(val_s, val_c)

        sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""
        direction = "Suicide > Control" if np.mean(val_s) > np.mean(val_c) else "Control > Suicide"

        stats_data.append({
            'Feature': col,
            'Suicide Mean': np.mean(val_s), 'Suicide SD': np.std(val_s),
            'Control Mean': np.mean(val_c), 'Control SD': np.std(val_c),
            'P-value': p,
            'Sig': sig,
            'Cohen_d': d_val,
            'Cliff_delta': delta_val,
            'Effect_Size_Grade': interpret_delta(delta_val),
            'Direction': direction
        })

    # 報表排序與匯出
    df_stats = pd.DataFrame(stats_data).sort_values('P-value', ascending=True)
    df_stats.to_excel(OUTPUT_STATS, index=False)

    print("-" * 140)
    print(f"{'Rank':<4} | {'Feature':<25} | {'P-value':<10} | {'Sig':<4} | {'Cohen d':<10} | {'Cliff Δ':<10} | {'Grade':<10} | {'Direction'}")
    print("-" * 140)

    for i, (idx, row) in enumerate(df_stats.iterrows()):
        print(f"{i+1:<4} | {row['Feature']:<25} | {row['P-value']:<10.4f} | {row['Sig']:<4} | {row['Cohen_d']:>10.3f} | {row['Cliff_delta']:>10.3f} | {row['Effect_Size_Grade']:<10} | {row['Direction']}")

    print("-" * 140)
    print(f"[執行成功] 學術統計報表已儲存至: {OUTPUT_STATS}")

if __name__ == '__main__':
    main()

# -*- coding: utf-8 -*-
"""
機器學習基準模型建構、SHAP 解釋與錯誤分析
(Baseline Modeling, SHAP Explanation, and Error Analysis)
"""



import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import shap
import IPython
from tqdm import tqdm
from transformers import BertTokenizer, BertModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.metrics import classification_report

# ==========================================
# 1. 環境設定
# ==========================================
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"[系統資訊] 運算裝置配置: {DEVICE}")

INPUT_DATA_PATH = '/content/drive/MyDrive/語料期末/final_dataset_for_ML.xlsx'
BERT_EMB_PATH = '/content/drive/MyDrive/語料期末/bert_embeddings_github_baseline.npy'

IMP_A_XLSX = '/content/drive/MyDrive/語料期末/RF_importance_data_github_baseline.xlsx'
IMP_A_PNG = '/content/drive/MyDrive/語料期末/RF_Importance_github_baseline.png'
IMP_C_PNG = '/content/drive/MyDrive/語料期末/ModelC_Fusion_Importance_github_baseline.png'
SHAP_HTML = '/content/drive/MyDrive/語料期末/SHAP_MentalBERT_Explanation_github_baseline.html'
ERROR_ANALYSIS_XLSX = '/content/drive/MyDrive/語料期末/Comparative_Error_Analysis_github_baseline.xlsx'

MODEL_NAME = 'zwzzz/Chinese-MentalBERT'

# ==========================================
# 2. 資料載入與特徵對齊
# ==========================================
print("\n[階段 1] 載入特徵資料集與文本...")
if not os.path.exists(INPUT_DATA_PATH):
    raise FileNotFoundError(f"[錯誤] 找不到資料集: {INPUT_DATA_PATH}")

df_ml = pd.read_excel(INPUT_DATA_PATH)
y = df_ml['final_label'].values
texts = df_ml['cleaned_content'].fillna("").astype(str).tolist()

drop_list = ['cleaned_content', 'ckip_tokens', 'pos_tags', 'Len', 'final_label']
X_manual_df = df_ml.drop(columns=drop_list)
X_manual = X_manual_df.values
manual_feature_names = X_manual_df.columns.tolist()

print(f"    - 手工特徵維度: {X_manual.shape}")
print(f"    - 樣本分布: 低風險組(0)={sum(y==0)}, 自殺風險組(1)={sum(y==1)}")

# ==========================================
# 3. 處理 MentalBERT 語意特徵
# ==========================================
print(f"\n[階段 2] 準備 MentalBERT 特徵...")
tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)

# 將 BERT 模型的初始化移至全域，確保只載入一次，避免 SHAP 分析時記憶體溢出
bert_model = BertModel.from_pretrained(MODEL_NAME).to(DEVICE)
bert_model.eval()

def get_bert_embeddings(text_list, batch_size=16):
    embeddings = []
    with torch.no_grad():

        for i in tqdm(range(0, len(text_list), batch_size), desc="提取 BERT 特徵", leave=False):
            batch_texts = text_list[i:i+batch_size]
            inputs = tokenizer(batch_texts, return_tensors='pt', padding=True, truncation=True, max_length=512).to(DEVICE)
            outputs = bert_model(**inputs)
            cls_emb = outputs.last_hidden_state[:, 0, :].cpu().numpy()
            embeddings.append(cls_emb)
    return np.vstack(embeddings)

if os.path.exists(BERT_EMB_PATH):
    print(f"    - 偵測到既有 BERT 向量，執行讀取: {BERT_EMB_PATH}")
    X_bert = np.load(BERT_EMB_PATH)
else:
    print(f"    - 未偵測到 BERT 向量，啟動模型萃取程序...")
    X_bert = get_bert_embeddings(texts)
    np.save(BERT_EMB_PATH, X_bert)
    print(f"    - BERT 向量已儲存至: {BERT_EMB_PATH}")

# 融合特徵 (Model C)
X_fusion = np.hstack((X_manual, X_bert))
bert_feature_names = [f"BERT_dim_{i}" for i in range(X_bert.shape[1])]
fusion_feature_names = manual_feature_names + bert_feature_names

# ==========================================
# 4. 統一資料切分 (Train/Test Split)
# ==========================================
print("\n[階段 3] 執行統一資料切分 (80/20)...")
idx = np.arange(len(y))
train_idx, test_idx = train_test_split(idx, test_size=0.20, random_state=42, stratify=y)

y_train, y_test = y[train_idx], y[test_idx]
texts_test = [texts[i] for i in test_idx]

# ==========================================
# 5. 模型訓練與評估模組
# ==========================================
def evaluate_and_train_model(X_tr, y_tr, X_te, y_te, model_name):
    print(f"\n[執行評估] {model_name} - 5-Fold 交叉驗證穩定性測試...")
    rf_model = RandomForestClassifier(
        n_estimators=200,
        class_weight='balanced_subsample',
        random_state=42,
        n_jobs=-1
    )

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_results = cross_validate(
        rf_model, X_tr, y_tr, cv=skf,
        scoring=['accuracy', 'f1_weighted', 'recall'], return_train_score=False
    )

    print(f"    -> 平均 Accuracy: {np.mean(cv_results['test_accuracy']):.4f} (+/- {np.std(cv_results['test_accuracy']):.4f})")
    print(f"    -> 平均 Weighted F1: {np.mean(cv_results['test_f1_weighted']):.4f}")

    print(f"[模型訓練] 正在獨立測試集上執行最終驗收...")
    rf_model.fit(X_tr, y_tr)
    y_pred = rf_model.predict(X_te)

    print(f"\n======= {model_name} 最終分類報告 =======")
    print(classification_report(y_te, y_pred, target_names=['Low Risk (0)', 'High Risk (1)']))

    return rf_model, y_pred

print("\n[階段 4] 啟動隨機森林模型訓練與驗收...")
model_A, pred_A = evaluate_and_train_model(X_manual[train_idx], y_train, X_manual[test_idx], y_test, "Model A：手工特徵基準模型")
model_B, pred_B = evaluate_and_train_model(X_bert[train_idx], y_train, X_bert[test_idx], y_test, "Model B：MentalBERT 語意模型")
model_C, pred_C = evaluate_and_train_model(X_fusion[train_idx], y_train, X_fusion[test_idx], y_test, "Model C：融合模型 (Manual + BERT)")

# ==========================================
# 6. 特徵重要性視覺化
# ==========================================
print("\n[階段 5] 繪製並匯出特徵重要性圖表...")
plt.style.use('seaborn-v0_8-whitegrid')

# --- Model A 視覺化 ---
importances_A = pd.Series(model_A.feature_importances_, index=manual_feature_names).sort_values(ascending=True)
plt.figure(figsize=(10, 8))
importances_A.plot(kind='barh', color='#2c3e50')
plt.title('Feature Importance Rank (Hand-crafted Features)', fontsize=14)
plt.xlabel('Gini Importance')
plt.tight_layout()
plt.savefig(IMP_A_PNG, dpi=300)
plt.show()

# 儲存 Model A 數據
df_imp_A = pd.DataFrame({'Feature': importances_A.index, 'Importance': importances_A.values}).sort_values('Importance', ascending=False)
df_imp_A.to_excel(IMP_A_XLSX, index=False)

# --- Model C 視覺化 (Top 20) ---
feat_imp_C_df = pd.DataFrame({
    'Feature': fusion_feature_names,
    'Importance': model_C.feature_importances_
}).sort_values('Importance', ascending=False).head(20)

plt.figure(figsize=(12, 8))
colors = ['#e74c3c' if not f.startswith('BERT') else '#95a5a6' for f in feat_imp_C_df['Feature']]
sns.barplot(x='Importance', y='Feature', data=feat_imp_C_df, palette=colors, hue='Feature', legend=False)
plt.title('Top 20 Features in Fusion Model\n(Red: Hand-crafted, Grey: BERT dimensions)', fontsize=16, fontweight='bold')
plt.xlabel('Gini Importance', fontsize=12)
plt.ylabel('Feature Name', fontsize=12)
plt.tight_layout()
plt.savefig(IMP_C_PNG, dpi=300)
plt.show()
print("    - 視覺化圖表與數據已成功儲存。")

# ==========================================
# 7. SHAP 深度學習文字視覺化
# ==========================================
print("\n[階段 6] 啟動 SHAP 文字解釋器...")

def predict_proba_pipeline(text_array):
    if isinstance(text_array, str): text_array = [text_array]
    else: text_array = list(text_array)
    emb = get_bert_embeddings(text_array, batch_size=16)
    return model_B.predict_proba(emb)

explainer = shap.Explainer(predict_proba_pipeline, shap.maskers.Text(tokenizer))
target_indices = [i for i, label in enumerate(y_test) if label == 1][:2]

if target_indices:
    texts_to_explain = [texts_test[i] for i in target_indices]
    shap_values = explainer(texts_to_explain)

    shap.initjs()
    html_output = shap.plots.text(shap_values, display=False)

    full_html = f"""
    <html>
        <head><meta charset="utf-8"></head>
        <body>
            <h2>MentalBERT SHAP 決策視覺化</h2>
            <p>紅色：增加自殺風險預測機率 | 藍色：降低自殺風險預測機率</p>
            {html_output}
        </body>
    </html>
    """
    with open(SHAP_HTML, "w", encoding="utf-8") as f:
        f.write(full_html)

    display(IPython.display.HTML(html_output))
    print(f"    - SHAP HTML 報告已儲存至: {SHAP_HTML}")
else:
    print("    - 測試集中沒有找到風險樣本供 SHAP 解釋。")

# ==========================================
# 8. 交叉錯誤分析 (Error Analysis)
# ==========================================
print("\n[階段 7] 執行模型預測差異情形分析...")
df_compare = pd.DataFrame({
    'Text': texts_test,
    'True_Label': y_test,
    'Pred_Model_A': pred_A,
    'Pred_Model_B': pred_B,
    'Pred_Model_C': pred_C
})

df_A_superior = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_A'] == 1) & (df_compare['Pred_Model_B'] == 0)]
df_B_superior = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_B'] == 1) & (df_compare['Pred_Model_A'] == 0)]
df_C_complementary = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_A'] == 0) & (df_compare['Pred_Model_B'] == 0) & (df_compare['Pred_Model_C'] == 1)]
df_common_failures = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_A'] == 0) & (df_compare['Pred_Model_B'] == 0) & (df_compare['Pred_Model_C'] == 0)]

print("\n[統計摘要] 模型預測差異情形")
print("-" * 60)
print(f"情境一 (Model A 預測成功，Model B 失敗): {len(df_A_superior)} 筆")
print(f"情境二 (Model B 預測成功，Model A 失敗): {len(df_B_superior)} 筆")
print(f"情境三 (僅 Model C 融合後預測成功): {len(df_C_complementary)} 筆")
print(f"情境四 (三模型共同漏判之盲區): {len(df_common_failures)} 筆")
print("-" * 60)

def print_text_samples(df, title, limit=3):
    if len(df) > 0:
        print(f"\n[文本檢視] {title}:")
        for i, text in enumerate(df['Text'].head(limit).tolist()):
            display_text = text[:150] + "..." if len(text) > 150 else text
            print(f"樣本 {i+1}:\n{display_text}\n{'-'*40}")

print_text_samples(df_A_superior, "情境一：語言學特徵表現優異之案例")
print_text_samples(df_B_superior, "情境二：語意模型表現優異之案例")
print_text_samples(df_common_failures, "情境四：模型共同盲區之案例")

df_compare.to_excel(ERROR_ANALYSIS_XLSX, index=False)
print(f"\n[執行程序] 交叉分析完成，完整數據已匯出至: {ERROR_ANALYSIS_XLSX}")

# -*- coding: utf-8 -*-
"""
進階機器學習模型建構：特徵標準化、SMOTEENN 與動態 PCA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from imblearn.combine import SMOTEENN
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.metrics import classification_report

# ==========================================
# 0. 檔案輸出路徑設定
# ==========================================
IMP_C_PNG_ADV = '/content/drive/MyDrive/語料期末/ModelC_Fusion_Importance_v4_SMOTEENN.png'
ERROR_ANALYSIS_XLSX_ADV = '/content/drive/MyDrive/語料期末/Comparative_Error_Analysis_v4_SMOTEENN.xlsx'

# ==========================================
# 1. 統一資料切分與進階前處理
# ==========================================
print("\n[階段 3] 執行資料切分與進階前處理 (StandardScaler + 動態 PCA + SMOTEENN)...")

# 1. 基礎切分 (80/20)
idx = np.arange(len(y))
train_idx, test_idx = train_test_split(idx, test_size=0.20, random_state=42, stratify=y)
y_train, y_test = y[train_idx], y[test_idx]
texts_test = [texts[i] for i in test_idx]

# 2. 特徵標準化 (確保 SMOTE 距離計算不被手工特徵主導)
scaler_manual = StandardScaler()
X_manual_train_scaled = scaler_manual.fit_transform(X_manual[train_idx])
X_manual_test_scaled = scaler_manual.transform(X_manual[test_idx])

# 3. 動態 PCA 降維 (保留 90% 語意變異數)
pca = PCA(n_components=0.90, random_state=42)
X_bert_pca_train = pca.fit_transform(X_bert[train_idx])
X_bert_pca_test = pca.transform(X_bert[test_idx])
print(f"    - PCA 動態降維完成，BERT 最終保留維度: {X_bert_pca_train.shape[1]} 維")

# 4. 重新建立融合特徵 (Scaled Manual + PCA BERT)
X_fusion_train = np.hstack((X_manual_train_scaled, X_bert_pca_train))
X_fusion_test = np.hstack((X_manual_test_scaled, X_bert_pca_test))

bert_feature_names = [f"BERT_PC_{i+1}" for i in range(X_bert_pca_train.shape[1])]
fusion_feature_names = manual_feature_names + bert_feature_names

# 5. 針對訓練集進行 SMOTEENN 過採樣與邊界清理
print("    - 正在執行 SMOTEENN 處理類別不平衡與雜訊清理...")
smote_enn = SMOTEENN(random_state=42)

# SMOTEENN 清理雜訊後，各矩陣長度可能略有不同，需獨立 fit_resample
X_manual_train_sm, y_train_sm_A = smote_enn.fit_resample(X_manual_train_scaled, y_train)
X_bert_train_sm, y_train_sm_B = smote_enn.fit_resample(X_bert_pca_train, y_train)
X_fusion_train_sm, y_train_sm_C = smote_enn.fit_resample(X_fusion_train, y_train)

# ==========================================
# 2. 模型訓練與完整評估模組
# ==========================================
print("\n[階段 4] 啟動隨機森林模型訓練與評估 (Model A, B, C)...")

def train_and_evaluate_model(X_tr, y_tr, X_te, y_te, model_name, max_feat='sqrt'):
    """封裝 5-Fold 交叉驗證與獨立測試集評估"""

    rf_model = RandomForestClassifier(
        n_estimators=300,
        max_depth=15,                   # 限制深度防止過度擬合假樣本
        min_samples_split=5,
        class_weight='balanced_subsample',
        max_features=max_feat,
        random_state=42,
        n_jobs=-1
    )

    # 執行 5-Fold 交叉驗證取得訓練集穩定性分數
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_results = cross_validate(
        rf_model, X_tr, y_tr, cv=skf,
        scoring=['accuracy', 'f1_weighted'], return_train_score=False
    )

    print(f"\n======= {model_name} =======")
    print(f"[訓練集 5-Fold 驗證] 平均 Accuracy: {np.mean(cv_results['test_accuracy']):.4f} (+/- {np.std(cv_results['test_accuracy']):.4f})")
    print(f"[訓練集 5-Fold 驗證] 平均 Weighted F1: {np.mean(cv_results['test_f1_weighted']):.4f}")

    # 在獨立測試集上進行最終訓練與預測
    rf_model.fit(X_tr, y_tr)
    y_pred = rf_model.predict(X_te)

    print(f"\n[獨立測試集最終報告]")
    print(classification_report(y_te, y_pred, target_names=['Low Risk (0)', 'High Risk (1)']))

    return rf_model, y_pred

model_A, pred_A = train_and_evaluate_model(X_manual_train_sm, y_train_sm_A, X_manual_test_scaled, y_test, "Model A：手工特徵基準模型")
model_B, pred_B = train_and_evaluate_model(X_bert_train_sm, y_train_sm_B, X_bert_pca_test, y_test, "Model B：MentalBERT 語意模型 (PCA 降維版)")
model_C, pred_C = train_and_evaluate_model(X_fusion_train_sm, y_train_sm_C, X_fusion_test, y_test, "Model C：融合模型 (Manual + BERT)", max_feat=0.15)

# ==========================================
# 3. 特徵重要性視覺化
# ==========================================
print("\n[階段 5] 繪製並匯出特徵重要性圖表...")
plt.style.use('seaborn-v0_8-whitegrid')

# Model C 重要性 (Top 20)
feat_imp_C_df = pd.DataFrame({
    'Feature': fusion_feature_names,
    'Importance': model_C.feature_importances_
}).sort_values('Importance', ascending=False).head(20)

plt.figure(figsize=(12, 8))
colors = ['#e74c3c' if not f.startswith('BERT') else '#95a5a6' for f in feat_imp_C_df['Feature']]

sns.barplot(
    x='Importance',
    y='Feature',
    data=feat_imp_C_df,
    hue='Feature',
    palette=colors,
    legend=False
)

plt.title('Top 20 Features in Fusion Model\n(Red: Hand-crafted, Grey: BERT Principal Components)', fontsize=16, fontweight='bold')
plt.xlabel('Gini Importance', fontsize=12)
plt.ylabel('Feature Name', fontsize=12)
plt.tight_layout()
plt.savefig(IMP_C_PNG_ADV, dpi=300)
plt.show()
print(f"    - 視覺化圖表已儲存至: {IMP_C_PNG_ADV}")

# ==========================================
# 4. 交叉錯誤分析 (Error Analysis)
# ==========================================
print("\n[階段 6] 執行模型預測差異情形分析...")
df_compare = pd.DataFrame({
    'Text': texts_test,
    'True_Label': y_test,
    'Pred_Model_A': pred_A,
    'Pred_Model_B': pred_B,
    'Pred_Model_C': pred_C
})

df_A_superior = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_A'] == 1) & (df_compare['Pred_Model_B'] == 0)]
df_B_superior = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_B'] == 1) & (df_compare['Pred_Model_A'] == 0)]
df_C_complementary = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_A'] == 0) & (df_compare['Pred_Model_B'] == 0) & (df_compare['Pred_Model_C'] == 1)]
df_common_failures = df_compare[(df_compare['True_Label'] == 1) & (df_compare['Pred_Model_A'] == 0) & (df_compare['Pred_Model_B'] == 0) & (df_compare['Pred_Model_C'] == 0)]

print("\n[統計摘要] 預測差異情形 (僅針對高風險樣本)")
print("-" * 60)
print(f"情境一 (Model A 預測成功，Model B 失敗): {len(df_A_superior)} 筆")
print(f"情境二 (Model B 預測成功，Model A 失敗): {len(df_B_superior)} 筆")
print(f"情境三 (僅 Model C 融合後預測成功): {len(df_C_complementary)} 筆")
print(f"情境四 (三模型共同漏判之盲區): {len(df_common_failures)} 筆")
print("-" * 60)

df_compare.to_excel(ERROR_ANALYSIS_XLSX_ADV, index=False)
print(f"    - 交叉分析完整數據已匯出至: {ERROR_ANALYSIS_XLSX_ADV}")